### ISSUE TITLE
Add display of status "dringlicher Kurs geplant"

### ISSUE THREAD

**Issue by sarahkami** [lauralindal/dein-semesterplaner#101]
if an urgent module is selected, the color should change to green with red outline.

**Comment by noobiba** [comment]
Today we decided to delete this status information from the legend above the module plan. So there might be no need to display it in the module pool. 
But the question is: Should the user be reminded again if I try to delete this module from module pool? (Not inserted in our user stories) Or might it be better to have it visually differed from the other buttons? The user might hesitate to delete this module if it is visually different to the other green modules. What do you think?

**Comment by lauralindal** [comment]
Should be solved in a different ticket, if we decide to implement an extra warning. but we can close this for now, I'd say.
