### ISSUE TITLE
Change Webpack to hot reloading

### ISSUE THREAD

**Issue by lauralindal** [lauralindal/dein-semesterplaner#14]
We'll need two servers:
- webpack dev to compile javascript to be shown in browser (into one large script) - will also show errors live
- hoodie

**Comment by lauralindal** [comment]
See https://medium.com/@rajaraodv/webpack-the-confusing-parts-58712f8fcad9#.vg8h0vqim for hints.

**Comment by lauralindal** [comment]
So, it looks like noone has ever used HMR with React & Hoodie. It's seems quite complex to me and since it's not super valuable, I opted for nodemon. It hot reloads, too. But not individual modules - since our project is small, that should be okay. What do you think, @bastianalbers?

**Comment by bastianalbers** [comment]
Yeah, if the project is small enough it should be fine and not too slow, true.

**Comment by bastianalbers** [comment]
It might be a possibility to run just the server parts of hoodie without serving the frontend and have that served by webpack-dev-server in development and pull the hoodie client libs in there. But i didn't have the time to give that setup a try yet.

**Comment by lauralindal** [comment]
I'm okay with what we have now, if there's a better version, we can still open a new ticket :)
