### ISSUE TITLE
Create Glossary in Readme

### ISSUE THREAD

**Issue by lauralindal** [lauralindal/dein-semesterplaner#24]

**Comment by lauralindal** [comment]
@lenakoester @Maplerable What's the status here... Do we need to keep the ticket open or have you collected all the information so far?

**Comment by ghost** [comment]
I think it should be okay for the moment, but still needs to be updated along the way... We should probably briefly discuss it tomorrow and then move it to done for the current sprint? And since we like tickets so much we could create a new one called "update glossary" for the next one ;)

**Comment by lauralindal** [comment]
Yes, that would be okay by me. I'd like to request that we chance the usage of gender pronouns to something more neutral. Like "his/her" or rather "their". In the next ticket then :)

**Comment by ghost** [comment]
No problem, I think there are only one or two of those anyway. And I already found a typo in the last line that I missed.
