### ISSUE TITLE
ksjdf

### ISSUE THREAD

**Issue by noobiba** [lauralindal/dein-semesterplaner#26]

**Comment by tzokoli** [comment]
Was ist das für ein Issue Tanja? xD

**Comment by zoepage** [comment]
Das hab ich mich auch schon gefragt ;)

**Comment by lauralindal** [comment]
@noobiba kann das weg? ;)

**Comment by noobiba** [comment]
Entschuldigt die Verwirrung. Das war ein Test, um neue Cards anzulegen. Ich hatte es danach nicht gelöscht. Ich lösche es jetzt.

**Comment by lauralindal** [comment]
:+1:
