### ISSUE TITLE
Documentation: Accessibility for University-Websites

### ISSUE THREAD

**Issue by sarahkami** [lauralindal/dein-semesterplaner#27]

**Comment by Maplerable** [comment]
[Protokoll zur Recherche von Barrierefreiheit_21.11.16.pdf](https://github.com/lauralindal/dein-semesterplaner/files/614794/Protokoll.zur.Recherche.von.Barrierefreiheit_21.11.16.pdf)
[BITV 2.0 Anforderungen prüfen.pdf](https://github.com/lauralindal/dein-semesterplaner/files/614795/BITV.2.0.Anforderungen.prufen.pdf)

**Comment by lauralindal** [comment]
@Maplerable Ist das Ticket mit den beiden Dokumenten nun erledigt oder recherchierst du noch weiter?
