### ISSUE TITLE
2.3 Insert functionality to course schedule

### ISSUE THREAD

**Issue by noobiba** [lauralindal/dein-semesterplaner#30]
Als Studentin möchte ich aus den für das aktuelle Semester gewählten Kursen einen Stundenplan generieren lassen, damit ich überprüfen kann, ob es zeitliche Überschneidungen gibt.

Fragen/ Anmerkung:
- Darstellung von Überschneidung?
- zeitliche Eingrenzung vom Stundenplan? (Zeit und Wochentage)
- Darstellung von Blockseminaren/ 2-Wochen Kurse/ Übungen
- Raumangabe

**Comment by lauralindal** [comment]
Solved in #88
