### ISSUE TITLE
5. Overview of advised courses

### ISSUE THREAD

**Issue by tzokoli** [lauralindal/dein-semesterplaner#5]
1. Als Studentin möchte ich sehen, wie alle Kurse meines Studienganges laut Regelstudien-ordnung pro Semester belegt werden sollen, damit ich den Überblick behalte.

Fragen/ Anmerkung: 
- aktuelle Studienordnung verwenden
- Wie werden AWEs gehandhabt?
- Anforderungen an Accessability?

**Comment by lauralindal** [comment]
Done in subtickets
